### ISSUE TITLE
v1 compatibility layer doesn't work with sub-modules

### ISSUE THREAD

**Issue by VolkerH** [pyapp-kit/pydantic-compat#9]
* pydantic-compat version: 0.1.1
* Python version: 3.11
* Operating System:

### Description

The recently added v1 namespace support (#8)  does not handle sub-modules correctly. 
E.g. you can do  `from pydantic_compat.v1 import BaseModel` but not `from from pydantic_compat.v1.fields`

### What I Did

```python
# use pydantic.v1 without pydantic_compat
In [2]: from pydantic.v1.fields import SHAPE_LIST

# now try with pydantic_compat
In [3]: from pydantic_compat.v1.fields import SHAPE_LIST
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pydantic_compat.v1.fields import SHAPE_LIST

ModuleNotFoundError: No module named 'pydantic_compat.v1.fields'; 'pydantic_compat.v1' is not a package

# just verify that pydantic_compat works without subpackages
In [4]: from pydantic_compat.v1 import BaseModel

```

**Comment by tlambert03** [comment]
Thanks @VolkerH  and good catch/point.

Honestly, that makes me want to just remove this module/feature altogether.  It's not really the point of pydantic-compat, (the convenience was added for @jni cause he's self-described lazy) :)

I could fix this, but it would entail either:
1. using `sys.meta_path` and a custom [MetaPathFinder](https://docs.python.org/3/library/importlib.html#importlib.abc.MetaPathFinder) that magically forwards imports to the appropriate real pydantic module.
2. literally mirror the entire module structure internally here. (ew.)

... and all that to save someone from having to do, in their own package:

```python
try:
    from pydantic.v1.fields import SHAPE_LIST
except ImportError:
    from pydantic.fields import SHAPE_LIST
```

what do you (both) think?  Would you rather have pydantic compat do magic to give you that one-liner import `from pydantic_compat.v1...` with arbitrary submodule access?  Or just drop the dependency and do the try/except yourself?

**Comment by VolkerH** [comment]
Well, I only came across this package as @jni pointed it out to me so I don't know the back story.
Given this caveat, I tend to agree with your feeling to drop this particular feature. 
It's not quite like the `from __future__ import ...` compatbililty thingies anyway as I would still have explicitly change any imports `from pydantic` to  `from_pydantic.compat.v1` and as you point out in that case one can just do the explicit try/except block. Being explicit probably also makes it more clear what is going on to anyone who has to read that code.

I was also a bit surprised that you didn't actually use this `pydantic_compat` package in `pyappkit.app_model` but rather have another built-in variety.

**Comment by tlambert03** [comment]
> I was also a bit surprised that you didn't actually use this pydantic_compat package in pyappkit.app_model but rather have another built-in variety.

your hunch was correct... I created that before this package existed and just hadn't gotten around to using it there.  I made a PR today though: https://github.com/pyapp-kit/app-model/pull/128

**Comment by tlambert03** [comment]
#10  would revert it

**Comment by jni** [comment]
(Having said that I still like the *principle* of having a single package out there for smooth migration between pydantic versions, rather than have everyone in the ecosystem do their own try/except and then slow migration over.)

**Comment by jni** [comment]
Having thought about the subpackage problem more and seeing [the `_pydantic_compat.py` file in the equivalent napari PR](https://github.com/napari/napari/pull/6358/files#diff-294a92f946dab363f9541653745418fadd87a0f6e98f1dd201d6725325776cf9), I am back to thinking that solving this properly in this package would be a valuable community contribution. @tlambert03 I don't know MetaPathFinder but if it solves the problem succinctly then it seems worthwhile to me. Without it, the alternatives for packages that want to do this now become:

- use try/except in every module that uses Pydantic
- flatten the namespace to suit internal usage, as in napari/napari#6358
- figure out MetaPathFinder internally

To me, having an authoritative package to do this seems like the best option for downstream packages.

**Comment by tlambert03** [comment]
I still don't know.  I think it seems like the kind of thing that takes each package like ~10 minutes to make a file like https://github.com/napari/napari/pull/6358 and be done with it.  And if you ever need to add something or find an issue with it, it's right there in your own library... no need to wait for `pydantic-compat` to fix it and release a new version.  And, the `v1` namespace is supposed to be a somewhat short-term solution anyway (for those who haven't had time to figure out cross-compatibility yet).

I did actually play a bit with MetaPathFinder, and got something sort of working, and then, of all things, _PySide2_ started complaining when the `__package__` attribute of a given module (`pydantic`) didn't match that of the spec (yes, even though it had nothing to do with PySide2).  So, the point there is that digging into redirecting the import mechanism itself is definitely black magic, and you're liable to find more unexpected things.  So I gave up on it.

most packages don't dig into the internals of pydantic as much as napari does, and may be able to just use `pydantic-compat` with a couple additional things.  For those that don't something like https://github.com/napari/napari/pull/6358 really *does* seem like a very reasonable, one-time fix.  

That said, if you or anyone does dig into it more and figures out an elegant solution (perhaps I didn't use meta path finder correctly, or perhaps there's a better strategy) short of mirroring the entire module tree here, I'm happy to host it!

**Comment by tlambert03** [comment]
ok I played more 😜

here's the simplest I can come up with:

```python
import sys
from importlib.abc import Loader, MetaPathFinder
from importlib.machinery import ModuleSpec
from importlib.util import find_spec, spec_from_loader


class RedirectLoader(Loader):
    """Loader that redirects imports to `real_module`."""

    def __init__(self, real_module: str) -> None:
        self.real_module = real_module

    def create_module(self, spec: ModuleSpec) -> types.ModuleType | None:
        # use default machinery for module creation.
        return None

    def exec_module(self, module: types.ModuleType) -> None:
        # This is where we handle the redirection.
        # import from the actual module and copy the attributes to our module.
        redirected_module = __import__(self.real_module, fromlist=["__name__"])
        for attr_name in dir(redirected_module):
            setattr(module, attr_name, getattr(redirected_module, attr_name))
        module.__name__ = self.real_module


class PydanticFinder(MetaPathFinder):
    """Finder that redirects imports from TARGET_MODULE to `pydantic[.v1]`."""

    TARGET_MODULE = "pydantic_compat.v1"

    def find_spec(
        self,
        fullname: str,
        pydantic_candidate: Sequence[str] | None,
        target: types.ModuleType | None = None,
    ) -> ModuleSpec | None:
        if fullname.startswith(self.TARGET_MODULE):
            for pydantic_candidate in ("pydantic.v1", "pydantic"):
                redirected = fullname.replace(self.TARGET_MODULE, pydantic_candidate)
                if spec := find_spec(redirected):
                    # if we find a real pydantic spec, redirect to it
                    return spec_from_loader(
                        fullname, RedirectLoader(redirected), origin=spec.origin
                    )
        return None


sys.meta_path.append(PydanticFinder())
```

This seems to work ok...  The main weirdness for now is that it reports a different module path depending on which version of pydantic is installed:


```python
from pydantic_compat.v1.fields import Field

print(Field)
print(Field.__module__)
```

with pydantic 1.10 installed:
```
<cyfunction Field at 0x109896f60>
pydantic.fields
```

with pydantic 2 installed:
```
<function Field at 0x10b51d620>
pydantic_compat.v1.fields
```

**Comment by tlambert03** [comment]
an equally appropriate thing to do might be to request that pydantic itself add v1 to pydantic v1.10 ?

**Comment by jni** [comment]
Haha that's what I call a successful nerd-sniping. 😂 Cool stuff @tlambert03!

Even though I really like the outcome (🙏), you seem to not be excited about maintaining this solution, and I suspect @Czaki won't be excited about depending on it, so I might have to resign myself to having the state of the art live embedded in this issue...

Perhaps I'll release it as a one-file package called `pydantic1_4eva`. 😂 

I think our other pydantic expert is @brisvag, I'd be interested to hear his opinion...

**Comment by Czaki** [comment]
Especially for 0.4.19 I prefer the embedded solution. 
For 0.5.0 I like to migrate on pydantic v2 (if there is someone who could do this) and put it on plugin maintainers to upgrade their plugins (for example to use the v1 namespace).

**Comment by brisvag** [comment]
> I think our other pydantic expert is @brisvag, I'd be interested to hear his opinion...

This is not really very pydantic-specifc, it's a packaging/versionsing issue. I guess I agree that magic here seems a bit much and potentially confusing.

**Comment by jni** [comment]
Sorry, I didn't necessarily mean within napari: if you use pydantic in other projects, would you be interested in using pydantic_compat to help with migration (first doing .v1, then migrating to v2 objects), or are you happy to roll your own solution, or are you just yoloing and going v2 everywhere anyway?

**Comment by brisvag** [comment]
I just don't feel that strongly about either solution, so I guess I don't think it's worth the time and effort :P

**Comment by tlambert03** [comment]
ok, looks this nerd has been sniped long enough on this :) closing, and reverted #8
